name: Build & Deploy main frontend

on:
  push:
    branches: [main]

jobs:
  ci-check:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Install dependencies
        run: npm ci --include=optional

      - name: Build Project
        run: npm run build
        env:
          VITE_API_BASE_URL: https://api.juweloonline.com/api/v1

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-dist
          path: dist/

  deploy-build-files:
    name: Deploy Static Build Files (main)
    runs-on: ubuntu-latest
    needs: [ci-check]
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-dist
          path: dist/

      - name: Upload new build files to temp directory
        uses: appleboy/scp-action@v0.1.5
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          source: 'dist/*'
          target: '/home/${{ secrets.VPS_USER }}/deploy-temp'

      - name: Move build files into /var/www/main/dist
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          script: |
            sudo mkdir -p /var/www/main/dist
            sudo rm -rf /var/www/main/dist/*

            sudo mv ~/deploy-temp/* /var/www/main/dist/

            sudo chown -R root:root /var/www/main/dist
            sudo chmod -R 755 /var/www/main/dist

            sudo rm -rf ~/deploy-temp
